//! On-disk state, written so that a power cut costs you a keystroke.
//!
//! Two kinds of state live here and they have different needs, which is why
//! they are stored differently rather than in one file:
//!
//!   - **The session snapshot** — open tabs, notepad text, and the half-typed
//!     command sitting at each prompt. Small, rewritten often, and the thing
//!     the user would actually miss. Every write is `fsync`'d into a temporary
//!     file and then renamed over the old one, so a crash mid-write leaves the
//!     *previous* complete snapshot rather than half of the new one.
//!   - **Scrollback** — append-only, potentially megabytes, and merely nice to
//!     have. Buffered and flushed periodically, because paying an `fsync` per
//!     chunk of `cargo build` output would make the terminal slow for the sake
//!     of output nobody would miss.
//!
//! The asymmetry is the point. Durability is bought where it matters.

use std::collections::HashMap;
use std::fs::{self, File, OpenOptions};
use std::io::{BufWriter, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use parking_lot::Mutex;
use tauri::Emitter;

/// Scrollback is trimmed once a tab's log passes this.
const SCROLLBACK_MAX: u64 = 2 * 1024 * 1024;
/// How much is kept when it is. The gap between the two is what stops a busy
/// tab from trimming on nearly every write.
const SCROLLBACK_KEEP: u64 = 768 * 1024;

const FLUSH_AFTER: Duration = Duration::from_millis(500);
const FLUSH_BYTES: usize = 64 * 1024;

pub struct Store {
    root: PathBuf,
    recorders: Mutex<HashMap<String, Recorder>>,
}

struct Recorder {
    file: BufWriter<File>,
    len: u64,
    buffered: usize,
    last_flush: Instant,
}

impl Store {
    /// Open (creating if needed) the app's state directory.
    pub fn open(root: PathBuf) -> Arc<Self> {
        let _ = fs::create_dir_all(root.join("scrollback"));
        Arc::new(Self {
            root,
            recorders: Mutex::new(HashMap::new()),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    fn session_path(&self) -> PathBuf {
        self.root.join("session.json")
    }

    fn settings_path(&self) -> PathBuf {
        self.root.join("settings.json")
    }

    fn scrollback_path(&self, id: &str) -> PathBuf {
        // Tab ids are generated by this app, never by the user, but a path is
        // being built from one — so anything that could climb out of the
        // directory is refused rather than sanitised into something else.
        self.root.join("scrollback").join(format!("{id}.log"))
    }

    /* ── Session snapshot ────────────────────────────────────────────── */

    /// Replace the snapshot atomically and durably.
    pub fn save_session(&self, json: &str) -> std::io::Result<()> {
        self.write_atomic(&self.session_path(), json)
    }

    pub fn load_session(&self) -> Option<String> {
        fs::read_to_string(self.session_path()).ok()
    }

    /* ── Settings ────────────────────────────────────────────────────── */

    /// The user's preferences, kept apart from the session on purpose.
    ///
    /// The session snapshot is this machine at this moment and is rewritten
    /// several times a second; settings are the file you would copy to a new
    /// machine. Sharing one file would mean a corrupt snapshot could cost you
    /// your theme, and there is no reason for the two to fail together.
    pub fn save_settings(&self, json: &str) -> std::io::Result<()> {
        self.write_atomic(&self.settings_path(), json)
    }

    pub fn load_settings(&self) -> Option<String> {
        fs::read_to_string(self.settings_path()).ok()
    }

    /// Write a file so that a crash leaves either the old contents or the new
    /// ones, never a half of either.
    fn write_atomic(&self, target: &Path, json: &str) -> std::io::Result<()> {
        let mut tmp = target.as_os_str().to_owned();
        tmp.push(".tmp");
        let tmp = PathBuf::from(tmp);

        {
            let mut file = File::create(&tmp)?;
            file.write_all(json.as_bytes())?;
            // Ordering matters: the bytes must be on the disk *before* anything
            // points at them, or a crash between the two leaves the name
            // pointing at a file that was never written.
            file.sync_all()?;
        }

        rename_replacing(&tmp, target)?;

        // The rename itself is a directory modification, and is not durable
        // until the directory is synced. Windows has no equivalent and needs
        // none here.
        #[cfg(unix)]
        if let Ok(dir) = File::open(&self.root) {
            let _ = dir.sync_all();
        }

        Ok(())
    }

    /* ── Scrollback ──────────────────────────────────────────────────── */

    /// Record shell output for `id`. Never fails loudly: losing scrollback is
    /// not worth interrupting a terminal session over.
    pub fn append_scrollback(&self, id: &str, bytes: &[u8]) {
        let mut recorders = self.recorders.lock();
        let recorder = match recorders.get_mut(id) {
            Some(recorder) => recorder,
            None => {
                let Some(recorder) = self.open_recorder(id) else {
                    return;
                };
                recorders.entry(id.to_string()).or_insert(recorder)
            }
        };

        if recorder.file.write_all(bytes).is_err() {
            return;
        }
        recorder.len += bytes.len() as u64;
        recorder.buffered += bytes.len();

        if recorder.buffered >= FLUSH_BYTES || recorder.last_flush.elapsed() >= FLUSH_AFTER {
            let _ = recorder.file.flush();
            recorder.buffered = 0;
            recorder.last_flush = Instant::now();
        }

        // Dropping the recorder flushes it, which has to happen before the file
        // is rewritten underneath it — and the handle must be gone before the
        // rewrite opens its own, or Windows refuses the second open.
        let outgrown = recorder.len > SCROLLBACK_MAX;
        if outgrown {
            recorders.remove(id);
            drop(recorders);
            self.trim_scrollback(id);
        }
    }

    fn open_recorder(&self, id: &str) -> Option<Recorder> {
        let path = self.scrollback_path(id);
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)
            .ok()?;
        let len = file.metadata().ok().map(|meta| meta.len()).unwrap_or(0);
        Some(Recorder {
            file: BufWriter::new(file),
            len,
            buffered: 0,
            last_flush: Instant::now(),
        })
    }

    pub fn flush_scrollback(&self, id: &str) {
        if let Some(recorder) = self.recorders.lock().get_mut(id) {
            let _ = recorder.file.flush();
            recorder.buffered = 0;
        }
    }

    /// Discard all but the tail of a tab's log.
    ///
    /// The cut is moved forward to the first line break so replay starts at a
    /// row boundary, and a reset is prepended because the escape sequence that
    /// last set a colour is very likely on the other side of the cut — without
    /// it, restored scrollback can come back tinted.
    fn trim_scrollback(&self, id: &str) {
        let path = self.scrollback_path(id);
        let Ok(mut file) = OpenOptions::new().read(true).write(true).open(&path) else {
            return;
        };
        let Ok(len) = file.metadata().map(|meta| meta.len()) else {
            return;
        };
        if len <= SCROLLBACK_KEEP {
            return;
        }

        let mut tail = Vec::new();
        if file.seek(SeekFrom::End(-(SCROLLBACK_KEEP as i64))).is_err()
            || file.read_to_end(&mut tail).is_err()
        {
            return;
        }

        let start = tail
            .iter()
            .position(|byte| *byte == b'\n')
            .map(|index| index + 1)
            .unwrap_or(0);

        let mut trimmed = Vec::with_capacity(tail.len() - start + 4);
        trimmed.extend_from_slice(b"\x1b[0m");
        trimmed.extend_from_slice(&tail[start..]);

        if file.seek(SeekFrom::Start(0)).is_err() {
            return;
        }
        if file.write_all(&trimmed).is_err() {
            return;
        }
        let _ = file.set_len(trimmed.len() as u64);
    }

    /// The recorded output for a tab, ready to be written straight back into
    /// the terminal. Invalid bytes are replaced rather than rejected, since a
    /// truncated log is still worth showing.
    pub fn read_scrollback(&self, id: &str) -> String {
        self.flush_scrollback(id);
        fs::read(self.scrollback_path(id))
            .map(|bytes| String::from_utf8_lossy(&bytes).into_owned())
            .unwrap_or_default()
    }

    pub fn drop_scrollback(&self, id: &str) {
        self.recorders.lock().remove(id);
        let _ = fs::remove_file(self.scrollback_path(id));
    }

    /// Replace a pane's recorded output wholesale, as an import does.
    ///
    /// The live recorder is dropped first — it holds an open handle and its own
    /// idea of the file's length, and writing underneath it would leave the two
    /// disagreeing and append the next chunk at the wrong offset.
    pub fn replace_scrollback(&self, id: &str, bytes: &[u8]) {
        self.recorders.lock().remove(id);
        let _ = fs::create_dir_all(self.root.join("scrollback"));
        let _ = fs::write(self.scrollback_path(id), bytes);
    }

    /// Delete logs for tabs the snapshot no longer mentions.
    ///
    /// Run at startup: a tab closed during a crash never got its own delete,
    /// and without this the directory only ever grows.
    pub fn prune_scrollback(&self, keep: &[String]) {
        let Ok(entries) = fs::read_dir(self.root.join("scrollback")) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_none_or(|ext| ext != "log") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
                continue;
            };
            if !keep.iter().any(|id| id == stem) {
                let _ = fs::remove_file(&path);
            }
        }
    }
}

/// `rename` over an existing file, with a short retry.
///
/// Windows can briefly refuse this with a sharing violation when an indexer or
/// virus scanner has the destination open — a condition that clears on its own
/// and should not be allowed to lose a snapshot.
fn rename_replacing(from: &Path, to: &Path) -> std::io::Result<()> {
    let mut last = match fs::rename(from, to) {
        Ok(()) => return Ok(()),
        Err(err) => err,
    };
    for attempt in 1..=4 {
        std::thread::sleep(Duration::from_millis(10 * attempt));
        match fs::rename(from, to) {
            Ok(()) => return Ok(()),
            Err(err) => last = err,
        }
    }
    Err(last)
}

/* ── Commands ────────────────────────────────────────────────────────────── */

#[tauri::command]
pub fn session_save(store: tauri::State<'_, Arc<Store>>, json: String) -> Result<(), String> {
    store
        .save_session(&json)
        .map_err(|err| format!("could not save the session: {err}"))
}

#[tauri::command]
pub fn session_load(store: tauri::State<'_, Arc<Store>>) -> Option<String> {
    store.load_session()
}

#[tauri::command]
pub fn session_dir(store: tauri::State<'_, Arc<Store>>) -> String {
    store.root().to_string_lossy().into_owned()
}

/// Announced to every window whenever the settings file changes.
///
/// Settings are edited in a window of their own, so two webviews hold a copy
/// and either may change it. Rather than have them talk to each other, the
/// backend — which owns the file — tells all of them at once. The window that
/// made the change hears its own announcement, recognises the value as the one
/// it already has, and does nothing, which is what stops this going round.
pub const SETTINGS_CHANGED_EVENT: &str = "settings://changed";

#[tauri::command]
pub fn settings_save(
    app: tauri::AppHandle,
    store: tauri::State<'_, Arc<Store>>,
    json: String,
) -> Result<(), String> {
    store
        .save_settings(&json)
        .map_err(|err| format!("could not save your settings: {err}"))?;
    // After the write, never before: a window that reacts by re-reading the
    // file must not be told about a value that is not in it yet.
    let _ = app.emit(SETTINGS_CHANGED_EVENT, json);
    Ok(())
}

#[tauri::command]
pub fn settings_load(store: tauri::State<'_, Arc<Store>>) -> Option<String> {
    store.load_settings()
}

#[tauri::command]
pub fn scrollback_read(store: tauri::State<'_, Arc<Store>>, id: String) -> String {
    store.read_scrollback(&id)
}

#[tauri::command]
pub fn scrollback_drop(store: tauri::State<'_, Arc<Store>>, id: String) {
    store.drop_scrollback(&id);
}

#[tauri::command]
pub fn scrollback_prune(store: tauri::State<'_, Arc<Store>>, keep: Vec<String>) {
    store.prune_scrollback(&keep);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_store() -> (Arc<Store>, PathBuf) {
        let root = std::env::temp_dir().join(format!(
            "jterm-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&root);
        (Store::open(root.clone()), root)
    }

    #[test]
    fn a_saved_session_reads_back() {
        let (store, root) = temp_store();
        store.save_session(r#"{"tabs":[]}"#).unwrap();
        assert_eq!(store.load_session().as_deref(), Some(r#"{"tabs":[]}"#));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn saving_twice_leaves_no_temporary_behind() {
        let (store, root) = temp_store();
        store.save_session("{}").unwrap();
        store.save_session(r#"{"a":1}"#).unwrap();
        assert_eq!(store.load_session().as_deref(), Some(r#"{"a":1}"#));
        assert!(
            !root.join("session.json.tmp").exists(),
            "the temporary file must be renamed away, not left as litter"
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn scrollback_is_trimmed_once_it_outgrows_the_cap() {
        let (store, root) = temp_store();
        let line = vec![b'x'; 4095];
        for _ in 0..700 {
            store.append_scrollback("tab", &line);
            store.append_scrollback("tab", b"\n");
        }
        store.flush_scrollback("tab");
        let len = fs::metadata(store.scrollback_path("tab")).unwrap().len();
        assert!(
            len <= SCROLLBACK_MAX,
            "log grew to {len} bytes, past the {SCROLLBACK_MAX} cap"
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn pruning_keeps_only_the_tabs_still_open() {
        let (store, root) = temp_store();
        store.append_scrollback("keep", b"a");
        store.append_scrollback("gone", b"b");
        store.flush_scrollback("keep");
        store.flush_scrollback("gone");
        store.prune_scrollback(&["keep".to_string()]);
        assert!(store.scrollback_path("keep").exists());
        assert!(!store.scrollback_path("gone").exists());
        let _ = fs::remove_dir_all(root);
    }
}
