//! On-disk state, written so that a power cut costs you a keystroke.
//!
//! Two kinds of state live here and they have different needs, which is why
//! they are stored differently rather than in one file:
//!
//!   - **The session snapshot** — open tabs, notepad text, and the half-typed
//!     command sitting at each prompt. Small, rewritten often, and the thing
//!     the user would actually miss. Every write is `fsync`'d into a temporary
//!     file and then renamed over the old one, so a crash mid-write leaves the
//!     *previous* complete snapshot rather than half of the new one.
//!   - **Scrollback** — append-only, potentially megabytes, and merely nice to
//!     have. Buffered and flushed periodically, because paying an `fsync` per
//!     chunk of `cargo build` output would make the terminal slow for the sake
//!     of output nobody would miss.
//!
//! The asymmetry is the point. Durability is bought where it matters.

use std::collections::HashMap;
use std::fs::{self, File, OpenOptions};
use std::io::{BufWriter, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use parking_lot::Mutex;
use tauri::Emitter;

/// Scrollback is trimmed once a tab's log passes this.
const SCROLLBACK_MAX: u64 = 2 * 1024 * 1024;
/// How much is kept when it is. The gap between the two is what stops a busy
/// tab from trimming on nearly every write.
const SCROLLBACK_KEEP: u64 = 768 * 1024;

const FLUSH_AFTER: Duration = Duration::from_millis(500);
const FLUSH_BYTES: usize = 64 * 1024;

/// Pane ids become filenames in both persistence stores. Keep this rule in
/// one place so scrollback cannot accidentally accept a path that history
/// rejects (particularly during import, where ids come from an arbitrary
/// file).
/// The window whose snapshot is the app's own restore point.
pub const MAIN_WINDOW: &str = "main";

/// Window labels become filenames, so they are held to the same rule pane ids
/// are: nothing that could climb out of the directory, nothing unbounded.
pub(crate) fn valid_window_label(label: &str) -> bool {
    !label.is_empty()
        && label.len() <= 64
        && label
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '-' || ch == '_')
}

pub(crate) fn valid_pane_id(id: &str) -> bool {
    !id.is_empty() && id.len() <= 64 && id.chars().all(|ch| ch.is_ascii_alphanumeric() || ch == '-')
}

pub struct Store {
    root: PathBuf,
    recorders: Mutex<HashMap<String, Recorder>>,
}

struct Recorder {
    file: BufWriter<File>,
    len: u64,
    buffered: usize,
    last_flush: Instant,
}

impl Store {
    /// Open (creating if needed) the app's state directory.
    pub fn open(root: PathBuf) -> Arc<Self> {
        let _ = fs::create_dir_all(root.join("scrollback"));
        Arc::new(Self {
            root,
            recorders: Mutex::new(HashMap::new()),
        })
    }

    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Where one window's snapshot lives.
    ///
    /// The main window keeps `session.json`, unchanged and unversioned, because
    /// it is the file every previous release wrote and reading it back is how a
    /// session survives an upgrade. Every other window gets a file named after
    /// its label beside it.
    fn session_path(&self, window: &str) -> PathBuf {
        if window == MAIN_WINDOW {
            self.root.join("session.json")
        } else {
            self.root.join(format!("session-{window}.json"))
        }
    }

    fn recents_path(&self) -> PathBuf {
        self.root.join("recents.json")
    }

    fn settings_path(&self) -> PathBuf {
        self.root.join("settings.json")
    }

    fn scrollback_path(&self, id: &str) -> Option<PathBuf> {
        // Tab ids are generated by this app, never by the user, but a path is
        // being built from one — so anything that could climb out of the
        // directory is refused rather than sanitised into something else.
        valid_pane_id(id).then(|| self.root.join("scrollback").join(format!("{id}.log")))
    }

    /* ── Session snapshot ────────────────────────────────────────────── */

    /// Replace one window's snapshot atomically and durably.
    pub fn save_session(&self, window: &str, json: &str) -> std::io::Result<()> {
        self.write_atomic(&self.session_path(window), json)
    }

    pub fn load_session(&self, window: &str) -> Option<String> {
        fs::read_to_string(self.session_path(window)).ok()
    }

    /// Forget a window's snapshot, because the window was closed on purpose.
    ///
    /// The asymmetry this creates is the feature, and it is the same one tmux
    /// sessions get: a window you closed stays closed, and a window that was
    /// taken from you by a crash comes back. The main window is exempt — its
    /// file is the app's own restore point, and closing it is how you quit.
    pub fn drop_session(&self, window: &str) {
        if window == MAIN_WINDOW {
            return;
        }
        let _ = fs::remove_file(self.session_path(window));
    }

    /// The labels of the extra windows that have a snapshot on disk.
    ///
    /// What the main window reopens at launch. The main window itself is never
    /// in the list: it exists before anything here is asked.
    pub fn session_windows(&self) -> Vec<String> {
        let Ok(entries) = fs::read_dir(&self.root) else {
            return Vec::new();
        };
        let mut labels: Vec<String> = entries
            .flatten()
            .filter_map(|entry| {
                let name = entry.file_name().into_string().ok()?;
                let label = name.strip_prefix("session-")?.strip_suffix(".json")?;
                valid_window_label(label).then(|| label.to_string())
            })
            .collect();
        // Sorted so the windows come back in a stable order rather than in
        // whatever order the directory happens to be read in.
        labels.sort();
        labels
    }

    /* ── Recently opened, recently closed ────────────────────────────── */

    /// One entry moved to the front of the list.
    ///
    /// Read-modify-write here rather than in the frontend because more than one
    /// window can be open and all of them share this file. A window that read
    /// the list, added to it and wrote it back would lose whatever another
    /// window did in between; doing it in the process that owns the file means
    /// there is one list and one writer.
    ///
    /// Entries are opaque: the shape belongs to the frontend, and the only
    /// field this side knows about is `key`, which is what "the same thing
    /// again" means. Anything without one is refused rather than stored,
    /// because an entry that cannot be deduplicated would fill the list with
    /// copies of itself.
    pub fn push_recent(&self, entry: &str, limit: usize) -> std::io::Result<()> {
        let parsed: serde_json::Value = serde_json::from_str(entry)
            .map_err(|err| std::io::Error::new(std::io::ErrorKind::InvalidData, err))?;
        let Some(key) = parsed
            .get("key")
            .and_then(|key| key.as_str())
            .map(str::to_owned)
        else {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "a recent entry needs a key",
            ));
        };

        let mut entries = self.recents();
        entries.retain(|existing| existing.get("key").and_then(|k| k.as_str()) != Some(&key));
        entries.insert(0, parsed);
        entries.truncate(limit.clamp(1, 500));

        self.write_atomic(
            &self.recents_path(),
            &serde_json::Value::Array(entries).to_string(),
        )
    }

    /// Everything remembered, newest first, as it is on disk.
    pub fn load_recents(&self) -> String {
        serde_json::Value::Array(self.recents()).to_string()
    }

    /// Drop one entry, for a file that has gone or a session nobody wants back.
    pub fn forget_recent(&self, key: &str) -> std::io::Result<()> {
        let mut entries = self.recents();
        let before = entries.len();
        entries.retain(|existing| existing.get("key").and_then(|k| k.as_str()) != Some(key));
        if entries.len() == before {
            return Ok(());
        }
        self.write_atomic(
            &self.recents_path(),
            &serde_json::Value::Array(entries).to_string(),
        )
    }

    /// The list as parsed values, or an empty one for a file that is missing,
    /// unreadable or not an array — none of which is worth an error: the
    /// recents list is a convenience, and losing it costs a menu.
    fn recents(&self) -> Vec<serde_json::Value> {
        fs::read_to_string(self.recents_path())
            .ok()
            .and_then(|text| serde_json::from_str::<serde_json::Value>(&text).ok())
            .and_then(|value| match value {
                serde_json::Value::Array(entries) => Some(entries),
                _ => None,
            })
            .unwrap_or_default()
    }

    /* ── Settings ────────────────────────────────────────────────────── */

    /// The user's preferences, kept apart from the session on purpose.
    ///
    /// The session snapshot is this machine at this moment and is rewritten
    /// several times a second; settings are the file you would copy to a new
    /// machine. Sharing one file would mean a corrupt snapshot could cost you
    /// your theme, and there is no reason for the two to fail together.
    pub fn save_settings(&self, json: &str) -> std::io::Result<()> {
        self.write_atomic(&self.settings_path(), json)
    }

    pub fn load_settings(&self) -> Option<String> {
        fs::read_to_string(self.settings_path()).ok()
    }

    /// Write a file so that a crash leaves either the old contents or the new
    /// ones, never a half of either.
    fn write_atomic(&self, target: &Path, json: &str) -> std::io::Result<()> {
        let mut tmp = target.as_os_str().to_owned();
        tmp.push(".tmp");
        let tmp = PathBuf::from(tmp);

        {
            let mut file = File::create(&tmp)?;
            file.write_all(json.as_bytes())?;
            // Ordering matters: the bytes must be on the disk *before* anything
            // points at them, or a crash between the two leaves the name
            // pointing at a file that was never written.
            file.sync_all()?;
        }

        rename_replacing(&tmp, target)?;

        // The rename itself is a directory modification, and is not durable
        // until the directory is synced. Windows has no equivalent and needs
        // none here.
        #[cfg(unix)]
        if let Ok(dir) = File::open(&self.root) {
            let _ = dir.sync_all();
        }

        Ok(())
    }

    /* ── Scrollback ──────────────────────────────────────────────────── */

    /// Record shell output for `id`. Never fails loudly: losing scrollback is
    /// not worth interrupting a terminal session over.
    pub fn append_scrollback(&self, id: &str, bytes: &[u8]) {
        if !valid_pane_id(id) {
            return;
        }
        let mut recorders = self.recorders.lock();
        let recorder = match recorders.get_mut(id) {
            Some(recorder) => recorder,
            None => {
                let Some(recorder) = self.open_recorder(id) else {
                    return;
                };
                recorders.entry(id.to_string()).or_insert(recorder)
            }
        };

        if recorder.file.write_all(bytes).is_err() {
            return;
        }
        recorder.len += bytes.len() as u64;
        recorder.buffered += bytes.len();

        if recorder.buffered >= FLUSH_BYTES || recorder.last_flush.elapsed() >= FLUSH_AFTER {
            let _ = recorder.file.flush();
            recorder.buffered = 0;
            recorder.last_flush = Instant::now();
        }

        // Dropping the recorder flushes it, which has to happen before the file
        // is rewritten underneath it — and the handle must be gone before the
        // rewrite opens its own, or Windows refuses the second open.
        let outgrown = recorder.len > SCROLLBACK_MAX;
        if outgrown {
            recorders.remove(id);
            drop(recorders);
            self.trim_scrollback(id);
        }
    }

    fn open_recorder(&self, id: &str) -> Option<Recorder> {
        let path = self.scrollback_path(id)?;
        let file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)
            .ok()?;
        let len = file.metadata().ok().map(|meta| meta.len()).unwrap_or(0);
        Some(Recorder {
            file: BufWriter::new(file),
            len,
            buffered: 0,
            last_flush: Instant::now(),
        })
    }

    pub fn flush_scrollback(&self, id: &str) {
        if !valid_pane_id(id) {
            return;
        }
        if let Some(recorder) = self.recorders.lock().get_mut(id) {
            let _ = recorder.file.flush();
            recorder.buffered = 0;
        }
    }

    /// Discard all but the tail of a tab's log.
    ///
    /// The cut is moved forward to the first line break so replay starts at a
    /// row boundary, and a reset is prepended because the escape sequence that
    /// last set a colour is very likely on the other side of the cut — without
    /// it, restored scrollback can come back tinted.
    fn trim_scrollback(&self, id: &str) {
        let Some(path) = self.scrollback_path(id) else {
            return;
        };
        let Ok(mut file) = OpenOptions::new().read(true).write(true).open(&path) else {
            return;
        };
        let Ok(len) = file.metadata().map(|meta| meta.len()) else {
            return;
        };
        if len <= SCROLLBACK_KEEP {
            return;
        }

        let mut tail = Vec::new();
        if file.seek(SeekFrom::End(-(SCROLLBACK_KEEP as i64))).is_err()
            || file.read_to_end(&mut tail).is_err()
        {
            return;
        }

        let start = tail
            .iter()
            .position(|byte| *byte == b'\n')
            .map(|index| index + 1)
            .unwrap_or(0);

        let mut trimmed = Vec::with_capacity(tail.len() - start + 4);
        trimmed.extend_from_slice(b"\x1b[0m");
        trimmed.extend_from_slice(&tail[start..]);

        if file.seek(SeekFrom::Start(0)).is_err() {
            return;
        }
        if file.write_all(&trimmed).is_err() {
            return;
        }
        let _ = file.set_len(trimmed.len() as u64);
    }

    /// The recorded output for a tab, ready to be written straight back into
    /// the terminal. Invalid bytes are replaced rather than rejected, since a
    /// truncated log is still worth showing.
    pub fn read_scrollback(&self, id: &str) -> String {
        let Some(path) = self.scrollback_path(id) else {
            return String::new();
        };
        self.flush_scrollback(id);
        fs::read(path)
            .map(|bytes| String::from_utf8_lossy(&bytes).into_owned())
            .unwrap_or_default()
    }

    pub fn drop_scrollback(&self, id: &str) {
        let Some(path) = self.scrollback_path(id) else {
            return;
        };
        self.recorders.lock().remove(id);
        let _ = fs::remove_file(path);
    }

    /// Replace a pane's recorded output wholesale, as an import does.
    ///
    /// The live recorder is dropped first — it holds an open handle and its own
    /// idea of the file's length, and writing underneath it would leave the two
    /// disagreeing and append the next chunk at the wrong offset.
    pub fn replace_scrollback(&self, id: &str, bytes: &[u8]) -> Result<(), String> {
        let Some(path) = self.scrollback_path(id) else {
            return Err("invalid pane id".into());
        };
        self.recorders.lock().remove(id);
        fs::create_dir_all(self.root.join("scrollback"))
            .map_err(|err| format!("cannot create the scrollback directory: {err}"))?;
        fs::write(path, bytes).map_err(|err| format!("cannot replace scrollback: {err}"))
    }

    /// Delete logs for tabs the snapshot no longer mentions.
    ///
    /// Run at startup: a tab closed during a crash never got its own delete,
    /// and without this the directory only ever grows.
    pub fn prune_scrollback(&self, keep: &[String]) {
        let Ok(entries) = fs::read_dir(self.root.join("scrollback")) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_none_or(|ext| ext != "log") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else {
                continue;
            };
            if !keep.iter().any(|id| id == stem) {
                let _ = fs::remove_file(&path);
            }
        }
    }
}

/// `rename` over an existing file, with a short retry.
///
/// Windows can briefly refuse this with a sharing violation when an indexer or
/// virus scanner has the destination open — a condition that clears on its own
/// and should not be allowed to lose a snapshot.
fn rename_replacing(from: &Path, to: &Path) -> std::io::Result<()> {
    let mut last = match fs::rename(from, to) {
        Ok(()) => return Ok(()),
        Err(err) => err,
    };
    for attempt in 1..=4 {
        std::thread::sleep(Duration::from_millis(10 * attempt));
        match fs::rename(from, to) {
            Ok(()) => return Ok(()),
            Err(err) => last = err,
        }
    }
    Err(last)
}

/* ── Commands ────────────────────────────────────────────────────────────── */

/// Which window is asking.
///
/// Taken from the webview that made the call rather than from an argument: a
/// window's snapshot is its own, and there is no reason for one window to be
/// able to name another's file. An unrecognisable label falls back to the main
/// window's file, which is the safe end of the mistake — a session in the wrong
/// place beats a session written to a path built out of an arbitrary string.
fn window_key(window: &tauri::Window) -> String {
    let label = window.label();
    if valid_window_label(label) {
        label.to_string()
    } else {
        MAIN_WINDOW.to_string()
    }
}

#[tauri::command]
pub fn session_save(
    window: tauri::Window,
    store: tauri::State<'_, Arc<Store>>,
    json: String,
) -> Result<(), String> {
    store
        .save_session(&window_key(&window), &json)
        .map_err(|err| format!("could not save the session: {err}"))
}

#[tauri::command]
pub fn session_load(window: tauri::Window, store: tauri::State<'_, Arc<Store>>) -> Option<String> {
    store.load_session(&window_key(&window))
}

/// One window's snapshot, read by the window that reopens the others at launch.
#[tauri::command]
pub fn session_load_window(store: tauri::State<'_, Arc<Store>>, label: String) -> Option<String> {
    valid_window_label(&label)
        .then(|| store.load_session(&label))
        .flatten()
}

#[tauri::command]
pub fn session_drop(window: tauri::Window, store: tauri::State<'_, Arc<Store>>) {
    store.drop_session(&window_key(&window));
}

#[tauri::command]
pub fn session_windows(store: tauri::State<'_, Arc<Store>>) -> Vec<String> {
    store.session_windows()
}

/// How much is remembered. Long enough to find last week's session in, short
/// enough that the menu is a list rather than an archive.
const RECENTS_LIMIT: usize = 60;

#[tauri::command]
pub fn recents_list(store: tauri::State<'_, Arc<Store>>) -> String {
    store.load_recents()
}

#[tauri::command]
pub fn recents_push(store: tauri::State<'_, Arc<Store>>, entry: String) -> Result<(), String> {
    store
        .push_recent(&entry, RECENTS_LIMIT)
        .map_err(|err| format!("could not remember that: {err}"))
}

#[tauri::command]
pub fn recents_forget(store: tauri::State<'_, Arc<Store>>, key: String) -> Result<(), String> {
    store
        .forget_recent(&key)
        .map_err(|err| format!("could not forget that: {err}"))
}

#[tauri::command]
pub fn session_dir(store: tauri::State<'_, Arc<Store>>) -> String {
    store.root().to_string_lossy().into_owned()
}

/// Announced to every window whenever the settings file changes.
///
/// Settings are edited in a window of their own, so two webviews hold a copy
/// and either may change it. Rather than have them talk to each other, the
/// backend — which owns the file — tells all of them at once. The window that
/// made the change hears its own announcement, recognises the value as the one
/// it already has, and does nothing, which is what stops this going round.
pub const SETTINGS_CHANGED_EVENT: &str = "settings://changed";

#[tauri::command]
pub fn settings_save(
    app: tauri::AppHandle,
    store: tauri::State<'_, Arc<Store>>,
    json: String,
) -> Result<(), String> {
    store
        .save_settings(&json)
        .map_err(|err| format!("could not save your settings: {err}"))?;
    // After the write, never before: a window that reacts by re-reading the
    // file must not be told about a value that is not in it yet.
    let _ = app.emit(SETTINGS_CHANGED_EVENT, json);
    Ok(())
}

#[tauri::command]
pub fn settings_load(store: tauri::State<'_, Arc<Store>>) -> Option<String> {
    store.load_settings()
}

#[tauri::command]
pub fn scrollback_read(store: tauri::State<'_, Arc<Store>>, id: String) -> String {
    store.read_scrollback(&id)
}

#[tauri::command]
pub fn scrollback_drop(store: tauri::State<'_, Arc<Store>>, id: String) {
    store.drop_scrollback(&id);
}

#[tauri::command]
pub fn scrollback_prune(store: tauri::State<'_, Arc<Store>>, keep: Vec<String>) {
    store.prune_scrollback(&keep);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_store() -> (Arc<Store>, PathBuf) {
        let root = std::env::temp_dir().join(format!(
            "jterm-test-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&root);
        (Store::open(root.clone()), root)
    }

    #[test]
    fn a_saved_session_reads_back() {
        let (store, root) = temp_store();
        store.save_session(MAIN_WINDOW, r#"{"tabs":[]}"#).unwrap();
        assert_eq!(
            store.load_session(MAIN_WINDOW).as_deref(),
            Some(r#"{"tabs":[]}"#)
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn saving_twice_leaves_no_temporary_behind() {
        let (store, root) = temp_store();
        store.save_session(MAIN_WINDOW, "{}").unwrap();
        store.save_session(MAIN_WINDOW, r#"{"a":1}"#).unwrap();
        assert_eq!(
            store.load_session(MAIN_WINDOW).as_deref(),
            Some(r#"{"a":1}"#)
        );
        assert!(
            !root.join("session.json.tmp").exists(),
            "the temporary file must be renamed away, not left as litter"
        );
        let _ = fs::remove_dir_all(root);
    }

    /// Each window's snapshot is its own file, and the main window keeps the
    /// name every earlier release wrote — that file is how a session survives
    /// an upgrade.
    #[test]
    fn windows_keep_their_own_snapshots() {
        let (store, root) = temp_store();
        store.save_session(MAIN_WINDOW, r#"{"w":"main"}"#).unwrap();
        store.save_session("w-abc", r#"{"w":"second"}"#).unwrap();

        assert!(root.join("session.json").exists());
        assert!(root.join("session-w-abc.json").exists());
        assert_eq!(
            store.load_session("w-abc").as_deref(),
            Some(r#"{"w":"second"}"#)
        );
        assert_eq!(store.session_windows(), vec!["w-abc".to_string()]);

        let _ = fs::remove_dir_all(root);
    }

    /// A window closed on purpose stays closed; the main window's file is the
    /// app's restore point and is never dropped, because closing it is how you
    /// quit.
    #[test]
    fn dropping_forgets_a_window_but_never_the_main_one() {
        let (store, root) = temp_store();
        store.save_session(MAIN_WINDOW, "{}").unwrap();
        store.save_session("w-abc", "{}").unwrap();

        store.drop_session("w-abc");
        assert!(store.session_windows().is_empty());

        store.drop_session(MAIN_WINDOW);
        assert_eq!(store.load_session(MAIN_WINDOW).as_deref(), Some("{}"));

        let _ = fs::remove_dir_all(root);
    }

    /// Newest first, one copy of each thing, and capped.
    #[test]
    fn recents_keep_the_last_of_each_thing() {
        let (store, root) = temp_store();
        store
            .push_recent(r#"{"key":"file:/a","label":"a"}"#, 3)
            .unwrap();
        store
            .push_recent(r#"{"key":"file:/b","label":"b"}"#, 3)
            .unwrap();
        // The same thing again moves to the front rather than appearing twice.
        store
            .push_recent(r#"{"key":"file:/a","label":"a again"}"#, 3)
            .unwrap();

        let list: serde_json::Value = serde_json::from_str(&store.load_recents()).unwrap();
        let entries = list.as_array().unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0]["label"], "a again");
        assert_eq!(entries[1]["label"], "b");

        store.forget_recent("file:/a").unwrap();
        let after: serde_json::Value = serde_json::from_str(&store.load_recents()).unwrap();
        assert_eq!(after.as_array().unwrap().len(), 1);

        let _ = fs::remove_dir_all(root);
    }

    /// An entry with no key could not be deduplicated, so it is refused rather
    /// than allowed to fill the list with copies of itself.
    #[test]
    fn recents_refuse_an_entry_with_nothing_to_match_on() {
        let (store, root) = temp_store();
        assert!(store.push_recent(r#"{"label":"nameless"}"#, 10).is_err());
        assert!(store.push_recent("not json at all", 10).is_err());
        assert_eq!(store.load_recents(), "[]");
        let _ = fs::remove_dir_all(root);
    }

    /// A list that has been hand-edited into nonsense costs the menu, not the
    /// launch.
    #[test]
    fn recents_survive_a_file_that_is_not_a_list() {
        let (store, root) = temp_store();
        fs::write(root.join("recents.json"), "{\"not\":\"a list\"}").unwrap();
        assert_eq!(store.load_recents(), "[]");
        store.push_recent(r#"{"key":"file:/a"}"#, 10).unwrap();
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&store.load_recents())
                .unwrap()
                .as_array()
                .unwrap()
                .len(),
            1
        );
        let _ = fs::remove_dir_all(root);
    }

    /// The label reaches the filesystem, so anything that could climb out of
    /// the directory is refused rather than sanitised into something else.
    #[test]
    fn refuses_a_window_label_that_is_a_path() {
        assert!(valid_window_label("w-abc"));
        assert!(!valid_window_label("../../etc/passwd"));
        assert!(!valid_window_label(""));
        assert!(!valid_window_label(&"w".repeat(65)));
    }

    #[test]
    fn scrollback_is_trimmed_once_it_outgrows_the_cap() {
        let (store, root) = temp_store();
        let line = vec![b'x'; 4095];
        for _ in 0..700 {
            store.append_scrollback("tab", &line);
            store.append_scrollback("tab", b"\n");
        }
        store.flush_scrollback("tab");
        let len = fs::metadata(store.scrollback_path("tab").unwrap())
            .unwrap()
            .len();
        assert!(
            len <= SCROLLBACK_MAX,
            "log grew to {len} bytes, past the {SCROLLBACK_MAX} cap"
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn pruning_keeps_only_the_tabs_still_open() {
        let (store, root) = temp_store();
        store.append_scrollback("keep", b"a");
        store.append_scrollback("gone", b"b");
        store.flush_scrollback("keep");
        store.flush_scrollback("gone");
        store.prune_scrollback(&["keep".to_string()]);
        assert!(store.scrollback_path("keep").unwrap().exists());
        assert!(!store.scrollback_path("gone").unwrap().exists());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn scrollback_refuses_ids_that_are_paths() {
        let (store, root) = temp_store();
        let outside = root.with_extension("log");
        let absolute = outside.to_string_lossy();

        store.append_scrollback("../escape", b"append");
        assert!(store.replace_scrollback("../escape", b"replace").is_err());
        assert!(store.replace_scrollback(&absolute, b"absolute").is_err());

        assert!(!root.join("escape.log").exists());
        assert!(!outside.exists());
        assert_eq!(store.read_scrollback("../escape"), "");
        let _ = fs::remove_dir_all(root);
    }
}
